# Generated by Django 4.1.2 on 2022-11-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingaddress", old_name="product", new_name="order",
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.customer",
            ),
        ),
    ]
